"""add logo_url to eglise_parametres

Revision ID: 4d2641932640
Revises: 60918db5b32b
Create Date: 2026-06-24 07:34:00.686093

"""
from alembic import op
import sqlalchemy as sa
import models.models


# revision identifiers, used by Alembic.
revision = '4d2641932640'
down_revision = '60918db5b32b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eglise_parametres', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logo_url', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eglise_parametres', schema=None) as batch_op:
        batch_op.drop_column('logo_url')

    # ### end Alembic commands ###
