"""initial migration

Revision ID: 60918db5b32b
Revises: 
Create Date: 2026-06-23 07:41:08.612825

"""
from alembic import op
import sqlalchemy as sa
import models.models


# revision identifiers, used by Alembic.
revision = '60918db5b32b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=True),
    sa.Column('responsable_nom', sa.Text(), nullable=True),
    sa.Column('jour_reunion', sa.Text(), nullable=True),
    sa.Column('heure_reunion', sa.Text(), nullable=True),
    sa.Column('lieu_reunion', sa.Text(), nullable=True),
    sa.Column('couleur', sa.Text(), nullable=True),
    sa.Column('icone', sa.Text(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dons',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('membre_nom', sa.Text(), nullable=True),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('anonyme', sa.Boolean(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eglise_parametres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('ville', sa.Text(), nullable=True),
    sa.Column('telephone', sa.Text(), nullable=True),
    sa.Column('email_contact', sa.Text(), nullable=True),
    sa.Column('site_web', sa.Text(), nullable=True),
    sa.Column('facebook', sa.Text(), nullable=True),
    sa.Column('youtube', sa.Text(), nullable=True),
    sa.Column('instagram', sa.Text(), nullable=True),
    sa.Column('horaires', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('vision', sa.Text(), nullable=True),
    sa.Column('histoire', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('predications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('predicateur', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('serie', sa.Text(), nullable=True),
    sa.Column('resume', sa.Text(), nullable=True),
    sa.Column('fichier_url', sa.Text(), nullable=True),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'PASTEUR', 'SECRETAIRE', 'EQUIPE_MEDIA', 'CHEF_DEPARTEMENT', 'MEMBRE', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('annonces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('est_publique', sa.Boolean(), nullable=True),
    sa.Column('departement_id', sa.UUID(), nullable=True),
    sa.Column('date_publication', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_expiration', sa.DateTime(timezone=True), nullable=True),
    sa.Column('publie_par', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['publie_par'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('annonces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_annonces_est_publique'), ['est_publique'], unique=False)

    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('table_cible', sa.String(length=100), nullable=True),
    sa.Column('record_id', sa.UUID(), nullable=True),
    sa.Column('details', models.models.SafeJSONB(), nullable=True),
    sa.Column('ip_address', models.models.SafeINET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('chef_departement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('departement_id', sa.UUID(), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=True),
    sa.Column('date_fin', sa.Date(), nullable=True),
    sa.Column('is_actif', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'departement_id', name='_user_dept_uc')
    )
    op.create_table('communications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sujet', sa.Text(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('destinataires_type', sa.Text(), nullable=False),
    sa.Column('departement_id', sa.UUID(), nullable=True),
    sa.Column('departement_nom', sa.Text(), nullable=True),
    sa.Column('nb_destinataires', sa.Integer(), nullable=True),
    sa.Column('envoye_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statut', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nom', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fichier_url', sa.Text(), nullable=False),
    sa.Column('type_mime', sa.String(length=100), nullable=True),
    sa.Column('taille_bytes', sa.BigInteger(), nullable=True),
    sa.Column('est_public', sa.Boolean(), nullable=True),
    sa.Column('departement_id', sa.UUID(), nullable=True),
    sa.Column('uploade_par', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploade_par'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evenements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lieu', sa.Text(), nullable=True),
    sa.Column('type', sa.Text(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('public', sa.Boolean(), nullable=True),
    sa.Column('est_public', sa.Boolean(), nullable=True),
    sa.Column('departement_id', sa.UUID(), nullable=True),
    sa.Column('couleur', sa.Text(), nullable=True),
    sa.Column('cree_par', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['cree_par'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evenements_date_debut'), ['date_debut'], unique=False)

    op.create_table('galerie',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('fichier_url', sa.Text(), nullable=False),
    sa.Column('type_fichier', sa.String(length=10), nullable=True),
    sa.Column('evenement', sa.String(length=255), nullable=True),
    sa.Column('date_prise', sa.Date(), nullable=True),
    sa.Column('est_public', sa.Boolean(), nullable=True),
    sa.Column('ajoutee_par', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ajoutee_par'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('medias',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('PREDICATION', 'TEMOIGNAGE', 'CULTE', 'EVENEMENT', 'AUTRE', name='media_type'), nullable=False),
    sa.Column('youtube_url', sa.Text(), nullable=True),
    sa.Column('fichier_url', sa.Text(), nullable=True),
    sa.Column('thumbnail_url', sa.Text(), nullable=True),
    sa.Column('intervenant', sa.String(length=200), nullable=True),
    sa.Column('date_enregistrement', sa.Date(), nullable=True),
    sa.Column('duree_secondes', sa.Integer(), nullable=True),
    sa.Column('est_public', sa.Boolean(), nullable=True),
    sa.Column('publie_par', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['publie_par'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medias_type'), ['type'], unique=False)

    op.create_table('membres',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('prenom', sa.Text(), nullable=False),
    sa.Column('nom', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=True),
    sa.Column('telephone', sa.Text(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('quartier', sa.Text(), nullable=True),
    sa.Column('ville', sa.Text(), nullable=True),
    sa.Column('pays', sa.Text(), nullable=True),
    sa.Column('genre', sa.Text(), nullable=True),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('statut', sa.Text(), nullable=False),
    sa.Column('date_adhesion', sa.Date(), nullable=True),
    sa.Column('est_baptise', sa.Boolean(), nullable=True),
    sa.Column('date_bapteme', sa.Date(), nullable=True),
    sa.Column('photo_url', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membres_nom'), ['nom'], unique=False)
        batch_op.create_index(batch_op.f('ix_membres_user_id'), ['user_id'], unique=True)

    op.create_table('messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('expediteur_id', sa.UUID(), nullable=False),
    sa.Column('destinataire_id', sa.UUID(), nullable=False),
    sa.Column('sujet', sa.String(length=255), nullable=True),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('statut', sa.Enum('NON_LU', 'LU', 'ARCHIVE', name='message_status'), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['destinataire_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['expediteur_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['messages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_destinataire_id'), ['destinataire_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('EMAIL', 'INTERNE', 'SMS', name='notification_type'), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('lien', sa.Text(), nullable=True),
    sa.Column('est_lu', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('parametres_systeme',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('cle', sa.String(length=100), nullable=False),
    sa.Column('valeur', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cle')
    )
    op.create_table('password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('rapports_departement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('departement_id', sa.UUID(), nullable=False),
    sa.Column('mois', sa.Integer(), nullable=False),
    sa.Column('annee', sa.Integer(), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('nb_membres', sa.Integer(), nullable=True),
    sa.Column('nb_reunions', sa.Integer(), nullable=True),
    sa.Column('soumis_par', sa.UUID(), nullable=True),
    sa.Column('soumis_le', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['soumis_par'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('departement_id', 'mois', 'annee', name='_dept_period_uc')
    )
    op.create_table('reunions_departement',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('departement_id', sa.UUID(), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_reunion', sa.DateTime(timezone=True), nullable=False),
    sa.Column('lieu', sa.String(length=255), nullable=True),
    sa.Column('is_en_ligne', sa.Boolean(), nullable=True),
    sa.Column('lien_reunion', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('BAPTEME', 'AFFERMISSEMENT', 'FORMATION', 'EVANGELISATION', name='session_type'), nullable=False),
    sa.Column('titre', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_debut', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_fin', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lieu', sa.String(length=255), nullable=True),
    sa.Column('places_max', sa.Integer(), nullable=True),
    sa.Column('responsable_id', sa.UUID(), nullable=True),
    sa.Column('est_ouvert', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['responsable_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('finances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('DIME', 'OFFRANDE', 'DON', 'AUTRE', name='transaction_type'), nullable=False),
    sa.Column('montant', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('devise', sa.String(length=3), nullable=True),
    sa.Column('membre_id', sa.UUID(), nullable=True),
    sa.Column('est_anonyme', sa.Boolean(), nullable=True),
    sa.Column('date_transaction', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('recu_par', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recu_par'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finances_date_transaction'), ['date_transaction'], unique=False)

    op.create_table('inscriptions_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('membre_id', sa.UUID(), nullable=True),
    sa.Column('nom_prenom', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.Column('statut', sa.Enum('INSCRIT', 'CONFIRME', 'ANNULE', 'PRESENT', name='inscription_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('membre_departements',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('membre_id', sa.UUID(), nullable=False),
    sa.Column('departement_id', sa.UUID(), nullable=False),
    sa.Column('est_chef', sa.Boolean(), nullable=True),
    sa.Column('date_entree', sa.Date(), nullable=True),
    sa.Column('date_sortie', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['departement_id'], ['departements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membre_id', 'departement_id', name='_membre_dept_uc')
    )
    with op.batch_alter_table('membre_departements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_membre_departements_departement_id'), ['departement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_membre_departements_membre_id'), ['membre_id'], unique=False)

    op.create_table('presences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('membre_id', sa.UUID(), nullable=False),
    sa.Column('membre_nom', sa.Text(), nullable=False),
    sa.Column('evenement_id', sa.UUID(), nullable=False),
    sa.Column('evenement_titre', sa.Text(), nullable=False),
    sa.Column('evenement_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['evenement_id'], ['evenements.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('membre_id', 'evenement_id', name='_membre_evenement_uc')
    )
    op.create_table('presences_reunion',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reunion_id', sa.UUID(), nullable=False),
    sa.Column('membre_id', sa.UUID(), nullable=False),
    sa.Column('statut', sa.Enum('PRESENT', 'ABSENT', 'EXCUSE', name='presence_status'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('enregistre_par', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['enregistre_par'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reunion_id'], ['reunions_departement.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reunion_id', 'membre_id', name='_reunion_membre_uc')
    )
    op.create_table('rendez_vous',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('membre_id', sa.UUID(), nullable=True),
    sa.Column('nom_demandeur', sa.String(length=200), nullable=True),
    sa.Column('email_demandeur', sa.String(length=255), nullable=True),
    sa.Column('telephone_demandeur', sa.String(length=30), nullable=True),
    sa.Column('motif', sa.Text(), nullable=False),
    sa.Column('date_souhaitee', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_confirmee', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duree_minutes', sa.Integer(), nullable=True),
    sa.Column('lieu', sa.String(length=255), nullable=True),
    sa.Column('statut', sa.Enum('EN_ATTENTE', 'APPROUVE', 'REFUSE', 'ANNULE', 'TERMINE', name='rdv_status'), nullable=False),
    sa.Column('note_pasteur', sa.Text(), nullable=True),
    sa.Column('cree_par', sa.UUID(), nullable=True),
    sa.Column('approuve_par', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approuve_par'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['cree_par'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['membre_id'], ['membres.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rendez_vous', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rendez_vous_date_confirmee'), ['date_confirmee'], unique=False)
        batch_op.create_index(batch_op.f('ix_rendez_vous_statut'), ['statut'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rendez_vous', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rendez_vous_statut'))
        batch_op.drop_index(batch_op.f('ix_rendez_vous_date_confirmee'))

    op.drop_table('rendez_vous')
    op.drop_table('presences_reunion')
    op.drop_table('presences')
    with op.batch_alter_table('membre_departements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membre_departements_membre_id'))
        batch_op.drop_index(batch_op.f('ix_membre_departements_departement_id'))

    op.drop_table('membre_departements')
    op.drop_table('inscriptions_sessions')
    with op.batch_alter_table('finances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finances_date_transaction'))

    op.drop_table('finances')
    op.drop_table('sessions')
    op.drop_table('reunions_departement')
    op.drop_table('rapports_departement')
    op.drop_table('password_reset_tokens')
    op.drop_table('parametres_systeme')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))

    op.drop_table('notifications')
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_destinataire_id'))

    op.drop_table('messages')
    with op.batch_alter_table('membres', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_membres_user_id'))
        batch_op.drop_index(batch_op.f('ix_membres_nom'))

    op.drop_table('membres')
    with op.batch_alter_table('medias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medias_type'))

    op.drop_table('medias')
    op.drop_table('galerie')
    with op.batch_alter_table('evenements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evenements_date_debut'))

    op.drop_table('evenements')
    op.drop_table('documents')
    op.drop_table('communications')
    op.drop_table('chef_departement')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('annonces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_annonces_est_publique'))

    op.drop_table('annonces')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    op.drop_table('predications')
    op.drop_table('eglise_parametres')
    op.drop_table('dons')
    op.drop_table('departements')
    # ### end Alembic commands ###
