"""add must_change_password to users

Revision ID: aff287b26c58
Revises: 4d2641932640
Create Date: 2026-06-24 07:42:23.538231

"""
from alembic import op
import sqlalchemy as sa
import models.models


# revision identifiers, used by Alembic.
revision = 'aff287b26c58'
down_revision = '4d2641932640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('must_change_password', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('must_change_password')

    # ### end Alembic commands ###
